services:
  dev:
    restart: always
    image: snomura07/tron_base_img
    environment:
      - TZ=Asia/Tokyo
      - DISPLAY=${DISPLAY}  # WSLのDISPLAY変数をコンテナに渡す

    container_name: 'tron_dev'
    volumes:
      - ../src:/opt/tron/src
      - ../bin:/opt/tron/bin
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11ソケットを共有

    command: bash
    tty: true
